FROM python:3.12-slim


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/


WORKDIR /app

COPY pyproject.toml uv.lock* ./

RUN uv pip install --system -r pyproject.toml

COPY . .

ENV PYTHONPATH=/app

CMD ["taskiq", "worker", "app.background.taskiq.taskiq:broker", "--tasks-pattern", "app/background/taskiq/tasks/*.py"]
