"""made organization table point to user.

Revision ID: 0bbbc7cccce5
Revises: 45b93ed02ddf
Create Date: 2026-04-24 04:45:42.985354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbbc7cccce5'
down_revision: Union[str, Sequence[str], None] = '45b93ed02ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('organizations_name_key'), 'organizations', type_='unique')
    op.create_foreign_key(None, 'organizations', 'users', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('organizations', 'name')
    op.add_column('users', sa.Column('is_organization', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_organization')
    op.add_column('organizations', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_unique_constraint(op.f('organizations_name_key'), 'organizations', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('organizations', 'account_id')
    # ### end Alembic commands ###
