"""made all fields in UserProfile nullable.

Revision ID: 45b93ed02ddf
Revises: 1589d7c3311d
Create Date: 2026-04-23 20:18:44.024081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b93ed02ddf'
down_revision: Union[str, Sequence[str], None] = '1589d7c3311d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'github',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_profiles', 'linkedin',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'linkedin',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profiles', 'github',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
