"""add table to store dsa questions.

Revision ID: a6e8a9fd1022
Revises: 30b8fed6d645
Create Date: 2026-05-12 10:20:10.961738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6e8a9fd1022'
down_revision: Union[str, Sequence[str], None] = '30b8fed6d645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsa_questions',
    sa.Column('problem_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsa_questions_difficulty'), 'dsa_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_dsa_questions_job_role'), 'dsa_questions', ['job_role'], unique=False)
    op.create_index(op.f('ix_dsa_questions_topic'), 'dsa_questions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsa_questions_topic'), table_name='dsa_questions')
    op.drop_index(op.f('ix_dsa_questions_job_role'), table_name='dsa_questions')
    op.drop_index(op.f('ix_dsa_questions_difficulty'), table_name='dsa_questions')
    op.drop_table('dsa_questions')
    # ### end Alembic commands ###
